import '../styles/globals.css'
import "../flow/config"
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Header from '../components/Header'
import Loading from '../components/Loading'
import LoadingContext from '../hooks/LoadingContext'
import { useState } from 'react'
import Breadcrumb from '../components/Breadcrumb'

export default function App({ Component, pageProps }: AppProps) {

  const [isLoading, setIsLoading] = useState(false)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen'>
        <LoadingContext.Provider value={{ setIsLoading }}>
          <Header />
          {isLoading && <Loading />}
          <div className='w-full h-full px-8 pb-16 flex flex-col justify-center items-center flex-1'>
            <div className='w-fit'>
              <Breadcrumb />
              <Component {...pageProps}/>
            </div>
          </div>
        </LoadingContext.Provider>
      </main>
      <footer className='flex flex-1 py-8 mx-8 justify-center items-center border-t border-solid border-[#222]'   >
        <a
          href="https://github.com/gpfurlaneto"
          target="_blank"
          rel="noopener noreferrer"
        >
          Guilherme Furlaneto
        </a>
      </footer>
  </div>
  )
}
